export const aeroPreset = Object.freeze({
  id: "aero",
  calibrated: true,
  label: "Aero",
  zhLabel: "破风架",
  categoryLabel: "破风型",
  description: "标准公路车拓扑，使用接近水平的上管、粗壮下管与独立 Aero 前叉",
  template: "aero",
  topTubeStyle: "aero",
  downTubeStyle: "aero",
  topTubeProfile: "aero-horizontal",
  downTubeProfile: "aero-deep",
  seatTubeProfile: "standard-programmatic",
  headTubeProfile: "aero-deep",
  chainStayProfile: "aero-wide",
  forkProfile: "aero-deep",
  splitSeatTube: false,
  rearWheelCutout: false,
  aeroBbShell: true,
  seatStayStyle: null,
});
